CompileFlags:
  Add:
    - --cuda-path=/usr/local/cuda-12
    - -L/usr/local/cuda-12/lib64
    - -I/usr/local/cuda-12/include
    - --no-cuda-version-check
  Remove:
    - -Xcompiler*
    - -forward-unknown-to-host-compiler
    - --generate-code*
